apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: rs1
spec:
   replicas: 2
   selector: 
      env: system
      
   template:
      metadata: 
         name: firstpod
         labels:
            env: system
      spec:
         containers: 
            - name: c2
              image: httpd   

